# Generated by Django 3.2.15 on 2022-11-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact', '0003_auto_20161107_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='form_layout',
            field=models.CharField(choices=[('cmsplugin_contact.forms.ContactForm', 'default')], help_text='Choice the layout of contact form', max_length=255, verbose_name='Form Layout'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='recaptcha_theme',
            field=models.CharField(choices=[('clean', 'Clean'), ('red', 'Red'), ('white', 'White'), ('blackglass', 'Black Glass'), ('custom', 'Custom')], default='clean', max_length=20, verbose_name='ReCAPTCHA theme'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='spam_protection_method',
            field=models.SmallIntegerField(choices=[(0, 'Honeypot'), (1, 'Akismet'), (2, 'ReCAPTCHA')], default=0, verbose_name='Spam protection method'),
        ),
    ]
