# Generated by Django 4.2.3 on 2023-09-29 07:18

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название')),
                ('extension', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Расширение файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='Кол-во загрузок')),
                ('_file', filer.fields.file.FilerFileField(on_delete=django.db.models.deletion.CASCADE, to='filer.file', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'вложение',
                'verbose_name_plural': 'вложения',
                'ordering': ['-updated_at'],
            },
        ),
    ]
