version: '3.2'
services:
  ufkis-db-dev:
    image: postgres:15.3-alpine
    container_name: ufkis-db-dev
    networks:
      - default
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      #- ./my_db_scripts:/docker-entrypoint-initdb.d:ro
    env_file:
      - environment/dev.env
    restart: unless-stopped

  ufkis-app-dev:
    build: .
    container_name: ufkis-app-dev
    entrypoint: /entrypoint.sh
    networks:
      - default
      - proxy
    working_dir: /app
    ports:
      - "8001:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app:rw
        #- /etc/hosts:/etc/hosts:ro
    env_file:
      - environment/dev.env
    command: python manage.py runserver 0.0.0.0:80
    restart: unless-stopped
    depends_on:
      - ufkis-db-dev
      - ufkis-es-dev
      # - ufkis-solr-dev

  ufkis-es-dev:
    container_name: ufkis-es-dev
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - ./hunspell:/usr/share/elasticsearch/config/hunspell:ro
      # - "es_data:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
    networks:
      - default
  # ufkis-solr-dev:
  #   container_name: ufkis-solr-dev
  #   image: solr:6.6.6
  #   # environment:
  #     # - discovery.type=single-node
  #     # - xpack.security.enabled=false
  #   # volumes:
  #   #   - ./hunspell:/usr/share/elasticsearch/config/hunspell:ro
  #   ports:
  #     - "8983:8983"
  #   networks:
  #     - default
  #   command: #/opt/solr/bin/solr create -c tester -n basic_config
  #     - solr-precreate
  #     - tester

networks:
  proxy:
    name: 'proxy'
    external: true
  default:
    name: ufkis
