version: '3.2'
services:
  ufkis-db-dev:
    image: postgres:15.3-alpine
    container_name: ufkis-db-dev
    networks:
      - default
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      #- ./my_db_scripts:/docker-entrypoint-initdb.d:ro
    env_file:
      - environment/dev.env
    restart: unless-stopped

  ufkis-app-dev:
    build: .
    container_name: ufkis-app-dev
    entrypoint: /entrypoint.sh
    networks:
      - default
      - proxy
    working_dir: /app
    ports:
      - "8001:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./app:/app:rw
        #- /etc/hosts:/etc/hosts:ro
    env_file:
      - environment/dev.env
    command: python manage.py runserver 0.0.0.0:80
    restart: unless-stopped
    depends_on:
      - ufkis-db-dev
      - es-dev

  es-dev:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

networks:
  proxy:
    external:
      name: 'proxy'
  default:
    name: ufkis
