# Generated by Django 4.1.7 on 2023-07-09 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=256, verbose_name='Полное название')),
                ('short_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Краткое название')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Логотип')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.organization', verbose_name='Родительская организация')),
            ],
            options={
                'verbose_name': 'организация',
                'verbose_name_plural': 'организации',
            },
        ),
        migrations.CreateModel(
            name='Otdel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядковый номер')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'отдел',
                'verbose_name_plural': 'отделы',
            },
        ),
        migrations.CreateModel(
            name='Sotrudnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядковый номер')),
                ('lastname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('firstname', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Отчество')),
                ('position', models.CharField(max_length=128, verbose_name='Должность')),
                ('in_apparat', models.BooleanField(default=False, help_text='Если отмечено, сотрудник будет выведен                                   в разделе "Аппарат управления" организации', verbose_name='В аппарате управления')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.organization', verbose_name='Организация')),
                ('otdel', models.ForeignKey(blank=True, help_text='Если не заполнено, сотрудник будет                                 отображаться в разделе "Прочие сотрудники" организации', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.otdel', verbose_name='Отдел')),
                ('photo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
            },
        ),
    ]
