# Generated by Django 4.1.7 on 2023-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(default='hz', max_length=128, verbose_name='Краткое название'),
            preserve_default=False,
        ),
    ]
