# Generated by Django 4.1.7 on 2023-07-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_organization_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
