# Generated by Django 4.1.7 on 2023-07-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_organization_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='list_order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
