# Generated by Django 4.1.7 on 2023-07-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_organization_list_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['list_order'], 'verbose_name': 'организация', 'verbose_name_plural': 'организации'},
        ),
        migrations.AlterModelOptions(
            name='otdel',
            options={'ordering': ['organization', 'order'], 'verbose_name': 'отдел', 'verbose_name_plural': 'отделы'},
        ),
        migrations.AlterModelOptions(
            name='sotrudnik',
            options={'ordering': ['organization', 'otdel', 'order'], 'verbose_name': 'сотрудник', 'verbose_name_plural': 'сотрудники'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='otdel',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='sotrudnik',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок'),
        ),
    ]
