# Generated by Django 4.1.7 on 2023-07-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_alter_organization_options_alter_otdel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Телефон приемной'),
        ),
    ]
