# Generated by Django 4.1.7 on 2023-07-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_organization_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='shedule',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='График работы'),
        ),
    ]
