# Generated by Django 4.1.7 on 2023-07-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_organization_shedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
