# Generated by Django 4.1.7 on 2023-07-19 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_alter_organization_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sotrudnik',
            old_name='in_apparat',
            new_name='apparat',
        ),
    ]
