# Generated by Django 4.2.3 on 2023-08-05 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0015_phone_otdel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phone',
            old_name='phone',
            new_name='number',
        ),
    ]
