# Generated by Django 4.2.3 on 2023-08-05 08:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0016_rename_phone_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'телефон', 'verbose_name_plural': 'телефоны'},
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер'),
        ),
    ]
