# Generated by Django 4.2.3 on 2023-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0017_alter_phone_options_alter_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fax',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Факс приемной'),
        ),
    ]
