# Generated by Django 4.2.3 on 2023-08-30 04:31

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('structure', '0018_organization_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='content',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='content', to='cms.placeholder'),
        ),
    ]
