# Generated by Django 4.2.3 on 2023-08-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('structure', '0023_otdelorganizationplugin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SotrudnikOrganizationPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('layout', models.CharField(choices=[('rows', 'Построчно'), ('blocks', 'Блоки')], default='rows', verbose_name='Макет')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.organization', verbose_name='Организация')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
