# Generated by Django 4.2.3 on 2023-08-31 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0024_sotrudnikorganizationplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotrudnikorganizationplugin',
            name='apparat',
            field=models.BooleanField(default=False, help_text='Оставить только сотрудников аппарата (поле "Отдел" будет проигнорировано)', verbose_name='Только аппарат управления'),
        ),
        migrations.AddField(
            model_name='sotrudnikorganizationplugin',
            name='otdel',
            field=models.ForeignKey(blank=True, help_text='Если не заполнено, сотрудник будет                                 отображаться в разделе "Прочие сотрудники" организации', null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.otdel', verbose_name='Отдел'),
        ),
    ]
