# Generated by Django 4.2.3 on 2023-09-01 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0027_alter_organization_page_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='content',
        ),
    ]
