# Generated by Django 4.2.3 on 2023-09-10 06:47

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('structure', '0028_remove_organization_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='page_link',
            new_name='page',
        ),
        migrations.AddField(
            model_name='otdel',
            name='page',
            field=cms.models.fields.PageField(blank=True, help_text='Не обязательно', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page', verbose_name='Ссылка на страницу'),
        ),
        migrations.AddField(
            model_name='sotrudnik',
            name='page',
            field=cms.models.fields.PageField(blank=True, help_text='Не обязательно', null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.page', verbose_name='Ссылка на страницу'),
        ),
    ]
