# Generated by Django 4.2.3 on 2023-09-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0029_rename_page_link_organization_page_otdel_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otdelorganizationplugin',
            name='show_detail_link',
            field=models.BooleanField(default=False, help_text='если она есть', verbose_name='Отображать ссылку на страницу отделов'),
        ),
        migrations.AddField(
            model_name='sotrudnikorganizationplugin',
            name='show_detail_link',
            field=models.BooleanField(default=False, help_text='если она есть', verbose_name='Отображать ссылку на страницу сотрудников'),
        ),
    ]
