# Generated by Django 4.2.3 on 2023-09-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0030_otdelorganizationplugin_show_detail_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotrudnikorganizationplugin',
            name='show_detail_link',
            field=models.BooleanField(default=True, help_text='если она есть', verbose_name='Отображать ссылку на страницу сотрудников'),
        ),
    ]
