# Generated by Django 4.2.3 on 2023-09-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0032_alter_otdelorganizationplugin_show_detail_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otdelorganizationplugin',
            name='show_detail_link',
            field=models.BooleanField(default=True, help_text='если она есть', verbose_name='Отображать ссылку на страницы отделов и сотрудников'),
        ),
    ]
