# Generated by Django 4.2.3 on 2023-09-12 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0034_categoryorganization_organization_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryorganization',
            options={'verbose_name': 'вид организаций', 'verbose_name_plural': 'виды организаций'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structure.categoryorganization', verbose_name='Вид организации (не обязательно)'),
        ),
    ]
