# Generated by Django 4.2.3 on 2023-09-13 04:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0037_alter_activity_options_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='department',
            name='schedule',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Название'),
        ),
    ]
