# Generated by Django 4.2.3 on 2023-09-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0038_department_phone_department_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='schedule',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Режим работы'),
        ),
    ]
