# Generated by Django 4.2.3 on 2023-09-13 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('structure', '0039_alter_department_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.department')),
                ('photo', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
