# Generated by Django 4.2.3 on 2023-09-15 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('structure', '0041_alter_photodepartment_options_department_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('show_logo', models.BooleanField(verbose_name='Отображать')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
