# Generated by Django 4.2.3 on 2023-09-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0042_activityplugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplugin',
            name='show_logo',
        ),
        migrations.AddField(
            model_name='activityplugin',
            name='layout',
            field=models.CharField(choices=[('blocks', 'Блоки (без лого)'), ('image-blocks', 'Блоки с логотипом на фоне')], default='blocks', verbose_name='Макет'),
        ),
    ]
