# Generated by Django 4.2.3 on 2023-09-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('structure', '0043_remove_activityplugin_show_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.activity', verbose_name='Вид спорта')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
