# Generated by Django 4.1.7 on 2023-06-04 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breadcrumbs',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('_title', models.CharField(blank=True, default='', help_text='Не обязательно. Если не заполнено - будет использован заголовок страницы.', max_length=255, null=True, verbose_name='Заголовок')),
                ('thumb_width', models.PositiveSmallIntegerField(default=400, verbose_name='Ширина')),
                ('thumb_height', models.PositiveSmallIntegerField(default=200, verbose_name='Высота')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
