# Generated by Django 4.1.7 on 2023-06-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadcrumbs',
            name='thumb_height',
        ),
        migrations.RemoveField(
            model_name='breadcrumbs',
            name='thumb_width',
        ),
        migrations.AddField(
            model_name='breadcrumbs',
            name='height',
            field=models.PositiveSmallIntegerField(default=300, verbose_name='Высота'),
        ),
    ]
