# Generated by Django 4.1.7 on 2023-06-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0005_remove_breadcrumbs_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadcrumbs',
            name='thumb_height',
            field=models.PositiveSmallIntegerField(default=300, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='breadcrumbs',
            name='thumb_width',
            field=models.PositiveSmallIntegerField(default=400, verbose_name='Ширина'),
        ),
    ]
