# Generated by Django 4.2.6 on 2023-10-20 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0006_breadcrumbs_thumb_height_breadcrumbs_thumb_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadcrumbs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='breadcrumbs',
            name='thumb_height',
        ),
        migrations.RemoveField(
            model_name='breadcrumbs',
            name='thumb_width',
        ),
    ]
