# Generated by Django 3.2.15 on 2022-09-30 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimatedNumbers',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_animated_numbers_animatednumbers', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=999, verbose_name='Целевое число')),
                ('title', models.CharField(default='', max_length=256, verbose_name='Подпись')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_animated_numbers.animatednumbers')),
            ],
            options={
                'verbose_name': 'анимированное число',
                'verbose_name_plural': 'анимированные числа',
            },
        ),
    ]
