# Generated by Django 3.2.15 on 2022-09-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_animated_numbers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='number',
            options={'verbose_name': 'анимированный показатель', 'verbose_name_plural': 'анимированные показатели'},
        ),
        migrations.AddField(
            model_name='animatednumbers',
            name='duration',
            field=models.PositiveIntegerField(default=5000, verbose_name='Время действия анимации (миллисекунды, 1сек=1000мс)'),
        ),
        migrations.AlterField(
            model_name='number',
            name='number',
            field=models.IntegerField(default=999, verbose_name='Значение показателя'),
        ),
    ]
