# Generated by Django 3.2.15 on 2022-09-30 12:20

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('djangocms_animated_numbers', '0002_auto_20220930_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='animatednumbers',
            name='background_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фоновое изображение'),
        ),
    ]
