# Generated by Django 3.2.15 on 2022-10-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_animated_numbers', '0003_animatednumbers_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animatednumbers',
            name='background_image',
        ),
    ]
