# Generated by Django 3.2.15 on 2022-10-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_animated_numbers', '0004_remove_animatednumbers_background_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animatednumbers',
            name='text',
        ),
        migrations.RemoveField(
            model_name='animatednumbers',
            name='title',
        ),
    ]
