# Generated by Django 3.2.15 on 2022-10-13 04:37

import cms.models.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='news_newsplugin', serialize=False, to='cms.cmsplugin')),
                ('num_objects', models.PositiveIntegerField(default=3, verbose_name='Количество новостей')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=1000, verbose_name='Заголовок')),
                ('alias', models.SlugField(blank=True, default='', help_text="Краткое название транслитом через тире (пример: 'kratkoe-nazvanie-translitom'). Чем короче тем лучше. Для автоматического заполнения - оставьте пустым.", max_length=1000, unique=True)),
                ('published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('published_at', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('text', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', null=True, verbose_name='Содержимое')),
                ('image_position', models.CharField(choices=[('left', 'Слева'), ('stretch', 'Растянуть'), ('right', 'Справа'), ('hide', 'Скрыть')], default='left', max_length=64, verbose_name='Расположение изображения')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Изображение')),
                ('placeholder_bottom', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_bottom', slotname='bottom', to='cms.placeholder')),
                ('placeholder_top', cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_top', slotname='top', to='cms.placeholder')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-published_at'],
            },
        ),
    ]
