# Generated by Django 4.1.7 on 2023-03-21 08:34

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('news', '0003_alter_newsplugin_cmsplugin_ptr_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='placeholder_bottom',
        ),
        migrations.RemoveField(
            model_name='post',
            name='placeholder_top',
        ),
        migrations.AddField(
            model_name='post',
            name='placeholder',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_post', slotname='post', to='cms.placeholder'),
        ),
    ]
