# Generated by Django 4.1.7 on 2023-03-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_post_placeholder_bottom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='placeholder',
        ),
    ]
