# Generated by Django 4.2.3 on 2023-08-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_post_image_post_cover_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='PostCategory',
        ),
    ]
