# Generated by Django 4.2.3 on 2023-09-04 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_rename_category_postcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_position',
            field=models.CharField(choices=[('left', 'Слева'), ('fullwidth', 'Во всю ширину')], default='left', verbose_name='Расположение обложки'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.postcategory', verbose_name='Категория'),
        ),
    ]
