# Generated by Django 4.2.3 on 2023-09-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_post_poster_position_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster_position',
        ),
        migrations.AddField(
            model_name='post',
            name='poster_fullwidth',
            field=models.BooleanField(default=False, verbose_name='Обложка во всю ширину'),
        ),
    ]
