# Generated by Django 4.2.3 on 2023-09-04 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_remove_post_poster_position_post_poster_fullwidth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster_fullwidth',
        ),
    ]
