# Generated by Django 4.1.7 on 2023-03-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='item_layout',
            field=models.CharField(choices=[('img_left', 'Картинка слева'), ('img_full', 'Картинка во всю ширину')], default='img_left', max_length=64, verbose_name='Стиль отображения'),
        ),
    ]
