# Generated by Django 4.1.7 on 2023-03-12 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalogitem_item_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='description',
        ),
    ]
