# Generated by Django 4.1.7 on 2023-06-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_catalogitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='item_layout',
            field=models.CharField(choices=[('img-left', 'Картинка слева'), ('img-full', 'Картинка во всю ширину')], default='img-left', max_length=64, verbose_name='Стиль отображения'),
        ),
    ]
