# Generated by Django 4.1.7 on 2023-06-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_catalogitem_item_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='item_layout',
            field=models.CharField(choices=[('img_left', 'Картинка слева'), ('img_full', 'Картинка во всю ширину')], default='img_left', max_length=64, verbose_name='Стиль отображения'),
        ),
    ]
