# Generated by Django 4.1.7 on 2023-03-01 04:02

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infoblock',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Заголовок')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', null=True, verbose_name='Описание')),
                ('background_color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None, verbose_name='Цвет фона')),
                ('thumb_width', models.PositiveSmallIntegerField(default=400, verbose_name='Ширина')),
                ('thumb_height', models.PositiveSmallIntegerField(default=300, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'слайд',
                'verbose_name_plural': 'слайды',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
