# Generated by Django 4.1.7 on 2023-03-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoblock', '0002_slide_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='thumb_height',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='thumb_width',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='title',
        ),
        migrations.AddField(
            model_name='slide',
            name='container_type',
            field=models.CharField(choices=[('container', 'С отступами справа и слева'), ('container-fluid no-paddings', 'Во всю ширину')], default='container', max_length=64, verbose_name='Расположение контента'),
        ),
    ]
