# Generated by Django 4.1.7 on 2023-03-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoblock', '0003_remove_slide_description_remove_slide_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoblock',
            name='container_type',
            field=models.CharField(choices=[('container', 'С отступами справа и слева'), ('container-fluid no-paddings', 'Во всю ширину')], default='container', max_length=64, verbose_name='Расположение контента'),
        ),
    ]
