# Generated by Django 4.1.7 on 2023-03-01 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoblock', '0004_infoblock_container_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoblock',
            name='container_type',
        ),
    ]
