# Generated by Django 4.1.7 on 2023-03-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoblock', '0005_remove_infoblock_container_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoblock',
            name='height',
            field=models.PositiveSmallIntegerField(default=450, verbose_name='Высота слайдера'),
        ),
    ]
