# Generated by Django 4.2.6 on 2023-10-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoblock', '0006_infoblock_height'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
