# Generated by Django 3.2.15 on 2022-10-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0002_auto_20221001_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsection',
            name='css_classes',
            field=models.CharField(blank=True, default='', help_text='указать классы через пробел', max_length=256, null=True, verbose_name='CSS классы'),
        ),
    ]
