# Generated by Django 3.2.15 on 2022-10-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0003_backgroundsection_css_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsection',
            name='use_parallax',
            field=models.BooleanField(default=True, verbose_name='Использовать эффект параллакса'),
        ),
    ]
