# Generated by Django 3.2.15 on 2022-10-06 11:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0004_backgroundsection_use_parallax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backgroundsection',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='backgroundsection',
            name='background_color',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', help_text='Опция будет проигнорирована, если задано фоновое изображение', image_field=None, max_length=18, null=True, samples=None, verbose_name='Фоновый цвет'),
        ),
        migrations.AlterField(
            model_name='backgroundsection',
            name='use_overlay',
            field=models.BooleanField(default=False, verbose_name='Использовать оверлей'),
        ),
        migrations.AlterField(
            model_name='backgroundsection',
            name='use_parallax',
            field=models.BooleanField(default=False, verbose_name='Использовать эффект параллакса'),
        ),
    ]
