# Generated by Django 3.2.15 on 2022-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0005_auto_20221006_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsection',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Не обязательно', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='backgroundsection',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Не обязательно', max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
