# Generated by Django 3.2.15 on 2022-10-06 12:06

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0006_auto_20221006_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backgroundsection',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='backgroundsection',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', help_text='Не обязательно', max_length=255, null=True, verbose_name='Текст'),
        ),
    ]
