# Generated by Django 3.2.15 on 2022-10-06 12:47

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0007_auto_20221006_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsection',
            name='text_bottom',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', help_text='Не обязательно', null=True, verbose_name='Текст снизу секции'),
        ),
        migrations.AlterField(
            model_name='backgroundsection',
            name='text',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', help_text='Не обязательно', null=True, verbose_name='Текст'),
        ),
    ]
