# Generated by Django 3.2.15 on 2022-11-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0008_auto_20221006_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsection',
            name='thumb_height',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='backgroundsection',
            name='thumb_width',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ширина'),
        ),
    ]
