# Generated by Django 4.1.7 on 2023-02-28 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('background_section', '0009_auto_20221102_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsection',
            name='container_type',
            field=models.CharField(choices=[('container', 'С отступами справа и слева'), ('container-fluid no-paddings', 'Во всю ширину')], default='container', max_length=64, verbose_name='Расположение контента'),
        ),
        migrations.AlterField(
            model_name='backgroundsection',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
    ]
