# Generated by Django 4.1.7 on 2023-03-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0010_backgroundsection_container_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsection',
            name='padding_bottom',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Отступ снизу (px)'),
        ),
        migrations.AddField(
            model_name='backgroundsection',
            name='padding_top',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Отступ сверху (px)'),
        ),
    ]
