# Generated by Django 4.1.7 on 2023-03-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0012_remove_backgroundsection_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsection',
            name='use_blur',
            field=models.BooleanField(default=False, verbose_name='Использовать эффект размытия'),
        ),
    ]
