# Generated by Django 4.1.7 on 2023-06-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0013_backgroundsection_use_blur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundsection',
            name='overlay_opacity',
            field=models.CharField(choices=[('0', '0'), ('.1', '10%'), ('.25', '25%'), ('.5', '50%'), ('.75', '75%'), ('.90', '90%'), ('1', '100%')], default='.5', max_length=8, verbose_name='Прозрачность оверлея'),
        ),
    ]
