# Generated by Django 4.1.7 on 2023-07-04 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_section', '0015_remove_backgroundsection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundsection',
            name='title_align',
            field=models.CharField(choices=[('center', 'По центру'), ('left', 'Слева'), ('right', 'Справа')], default='center', max_length=16, verbose_name='Расположение заголовка'),
        ),
    ]
