# Generated by Django 3.2.15 on 2022-09-30 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_reviews', '0002_alter_review_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='photo',
        ),
    ]
