# Generated by Django 3.2.15 on 2022-10-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_reviews', '0003_remove_review_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='text',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='title',
        ),
    ]
