# Generated by Django 3.2.15 on 2022-10-14 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexMap',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_yandexmap_yandexmap', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='map title')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('zipcode', models.CharField(max_length=30, verbose_name='zip code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('content', models.CharField(blank=True, max_length=255, null=True, verbose_name='additional content')),
                ('zoom', models.IntegerField(blank=True, null=True, verbose_name='zoom level')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, help_text='Use latitude & longitude to fine tune the map possiton.', max_digits=10, null=True, verbose_name='latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='longitude')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
