# Generated by Django 4.2.3 on 2023-09-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_yandexmap', '0002_alter_yandexmap_cmsplugin_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexmap',
            name='address',
            field=models.CharField(max_length=150, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='yandexmap',
            name='city',
            field=models.CharField(max_length=100, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='yandexmap',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='дополнительно'),
        ),
        migrations.AlterField(
            model_name='yandexmap',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='широта'),
        ),
        migrations.AlterField(
            model_name='yandexmap',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='долгота'),
        ),
        migrations.AlterField(
            model_name='yandexmap',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='yandexmap',
            name='zipcode',
            field=models.CharField(max_length=30, verbose_name='почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='yandexmap',
            name='zoom',
            field=models.IntegerField(blank=True, null=True, verbose_name='zoom (уровень масштаба)'),
        ),
    ]
