# Generated by Django 4.2.3 on 2023-09-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_yandexmap', '0003_alter_yandexmap_address_alter_yandexmap_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexmap',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='yandexmap',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='yandexmap',
            name='title',
            field=models.CharField(default='карта', max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='yandexmap',
            name='zipcode',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='почтовый индекс'),
        ),
    ]
