# Generated by Django 4.2.3 on 2023-09-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_yandexmap', '0004_alter_yandexmap_address_alter_yandexmap_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yandexmap',
            name='title',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
    ]
