# Generated by Django 4.2.3 on 2023-09-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_yandexmap', '0005_alter_yandexmap_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yandexmap',
            name='content',
        ),
    ]
