# Generated by Django 4.1.7 on 2023-06-22 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        ('cms', '0022_auto_20180620_1551'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('medialer', '0004_rename_picture_pluginpicture'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PluginPicture',
            new_name='Picture',
        ),
    ]
