# Generated by Django 4.1.7 on 2023-06-22 10:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('cms', '0022_auto_20180620_1551'),
        ('medialer', '0006_alter_picture_cmsplugin_ptr'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Picture',
            new_name='PluginPicture',
        ),
    ]
