# Generated by Django 4.1.7 on 2023-06-26 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('medialer', '0008_albumpicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Описание'),
        ),
    ]
