# Generated by Django 4.1.7 on 2023-06-28 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialer', '0009_album_cover_image_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumpicture',
            name='album',
            field=models.ForeignKey(help_text='Если оставиь пустым, будет использовано изображение из альбома', on_delete=django.db.models.deletion.CASCADE, to='medialer.album', verbose_name='Альбом'),
        ),
    ]
