# Generated by Django 4.1.7 on 2023-06-28 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('medialer', '0010_alter_albumpicture_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=filer.fields.image.FilerImageField(blank=True, help_text='Если оставить пустым, будет использовано изображение из альбома', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medialer.album', verbose_name='Альбом'),
        ),
    ]
