# Generated by Django 4.1.7 on 2023-06-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialer', '0011_alter_album_cover_image_alter_albumpicture_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='description',
            new_name='_description',
        ),
    ]
