# Generated by Django 4.1.7 on 2023-06-29 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialer', '0012_rename_description_album__description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='_description',
            new_name='description',
        ),
    ]
