# Generated by Django 4.1.7 on 2023-06-29 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialer', '0013_rename__description_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumpicture',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medialer.album', verbose_name='Альбом'),
        ),
    ]
