# Generated by Django 4.1.7 on 2023-07-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medialer', '0014_alter_albumpicture_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumpicture',
            name='album',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='medialer.album', verbose_name='Альбом'),
            preserve_default=False,
        ),
    ]
