# Generated by Django 4.2.3 on 2023-09-03 08:21

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('medialer', '0015_alter_albumpicture_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginpicture',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='height',
            field=models.PositiveIntegerField(default=400, help_text='Высота плеера в пикселях', verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Ширина плеера в пикселях (по умолчанию ширина 100%)', null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='alignment',
            field=models.CharField(blank=True, choices=[('left', 'Слева'), ('right', 'Справа'), ('center', 'По центру')], max_length=255, verbose_name='Выравнивание'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='external_picture',
            field=models.URLField(blank=True, help_text='Если указано, переопределяет встроенное изображение. Некоторые параметры, такие как обрезка, неприменимы к внешним изображениям.', max_length=255, null=True, verbose_name='Ссылка на внешнее изображение'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Высота изображения в пикселях', null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='link_page',
            field=cms.models.fields.PageField(blank=True, help_text='Обернуть изображение в ссылку на страницу сайта', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page', verbose_name='Внутрення ссылка'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='link_target',
            field=models.CharField(blank=True, choices=[('_blank', 'Open in new window'), ('_self', 'Open in same window'), ('_parent', 'Delegate to parent'), ('_top', 'Delegate to top')], max_length=255, verbose_name='Цель ссылки'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='link_url',
            field=models.URLField(blank=True, help_text='Обернуть изображение в ссылку на внешний ресурс', max_length=2040, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='use_automatic_scaling',
            field=models.BooleanField(blank=True, default=True, verbose_name='Автоматическое масштабирование'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='use_crop',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обрезать изображение'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='use_no_cropping',
            field=models.BooleanField(blank=True, default=False, verbose_name='Использовать оригинальное изображение'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='use_upscale',
            field=models.BooleanField(blank=True, default=False, verbose_name='Увеличить изображение'),
        ),
        migrations.AlterField(
            model_name='albumpicture',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Ширина изображения в пикселях', null=True, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='alignment',
            field=models.CharField(blank=True, choices=[('left', 'Слева'), ('right', 'Справа'), ('center', 'По центру')], max_length=255, verbose_name='Выравнивание'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='external_picture',
            field=models.URLField(blank=True, help_text='Если указано, переопределяет встроенное изображение. Некоторые параметры, такие как обрезка, неприменимы к внешним изображениям.', max_length=255, null=True, verbose_name='Ссылка на внешнее изображение'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Высота изображения в пикселях', null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='link_page',
            field=cms.models.fields.PageField(blank=True, help_text='Обернуть изображение в ссылку на страницу сайта', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cms.page', verbose_name='Внутрення ссылка'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='link_target',
            field=models.CharField(blank=True, choices=[('_blank', 'Open in new window'), ('_self', 'Open in same window'), ('_parent', 'Delegate to parent'), ('_top', 'Delegate to top')], max_length=255, verbose_name='Цель ссылки'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='link_url',
            field=models.URLField(blank=True, help_text='Обернуть изображение в ссылку на внешний ресурс', max_length=2040, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='use_automatic_scaling',
            field=models.BooleanField(blank=True, default=True, verbose_name='Автоматическое масштабирование'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='use_crop',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обрезать изображение'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='use_no_cropping',
            field=models.BooleanField(blank=True, default=False, verbose_name='Использовать оригинальное изображение'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='use_upscale',
            field=models.BooleanField(blank=True, default=False, verbose_name='Увеличить изображение'),
        ),
        migrations.AlterField(
            model_name='pluginpicture',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text='Ширина изображения в пикселях', null=True, verbose_name='Ширина'),
        ),
    ]
