# Generated by Django 4.2.3 on 2023-09-03 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_attributes_field.fields
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        ('medialer', '0016_alter_pluginpicture_options_videoplayer_height_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoplayer',
            options={'verbose_name': 'видео'},
        ),
        migrations.AddField(
            model_name='videoplayer',
            name='source_file',
            field=filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.file', verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='videoplayer',
            name='attributes',
            field=djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Атрибуты'),
        ),
        migrations.AlterField(
            model_name='videoplayer',
            name='embed_link',
            field=models.CharField(blank=True, help_text='Используйте это поля для встраивания видео с внешних видеосервисов таких как Youtube, VK, Vimeo и др. ', max_length=255, verbose_name='Встраиваемое видео'),
        ),
        migrations.AlterField(
            model_name='videoplayer',
            name='parameters',
            field=djangocms_attributes_field.fields.AttributesField(blank=True, default=dict, verbose_name='Параметры'),
        ),
        migrations.AlterField(
            model_name='videoplayer',
            name='poster',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Обложка'),
        ),
    ]
