# Generated by Django 4.2.3 on 2023-09-04 02:25

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0015_alter_file_owner_alter_file_polymorphic_ctype_and_more'),
        ('medialer', '0017_alter_videoplayer_options_videoplayer_source_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoplayer',
            name='source_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='filer.file', verbose_name='Файл видео'),
        ),
    ]
