# Generated by Django 4.2.3 on 2023-10-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medialer', '0018_alter_videoplayer_source_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumpicture',
            options={'verbose_name': 'фото', 'verbose_name_plural': 'фото'},
        ),
    ]
