# Generated by Django 4.2.3 on 2023-08-14 04:22

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Соглашение')),
                ('target_email', models.EmailField(blank=True, help_text='На этот адрес будут приходить обращения из виртуальной приемной', max_length=254, null=True, verbose_name='E-mail')),
                ('userdata_form_text', djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Текст на форме заполнения данных пользователя')),
                ('message_form_text', djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Текст на форме заполнения обращения ')),
                ('success_text', djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Текст после успешной отправки обращения ')),
                ('valid_file_extensions', models.CharField(default='pdf, txt, doc, docx, xls, xlsx, ppt, pptx, odt, ods, odp, jpg, png, gif, tiff, zip', max_length=512, verbose_name='Разрешенные форматы файлов (через запятую)')),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурация',
            },
        ),
    ]
