# Generated by Django 4.2.3 on 2023-08-15 02:59

from django.db import migrations, models
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsettings',
            name='agreement_checkbox_text',
            field=models.CharField(default='Я прочитал(а) правила пользования виртуальной приемной', max_length=256, verbose_name='Текст галочки на форме соглашения'),
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='userdata_checkbox_text',
            field=models.CharField(default='Я соглашаюсь на обработку моих персональны данных', max_length=256, verbose_name='Текст галочки на форме данных пользователя'),
        ),
        migrations.AlterField(
            model_name='contactsettings',
            name='userdata_form_text',
            field=djangocms_text_ckeditor.fields.HTMLField(default='', verbose_name='Текст на форме данных пользователя'),
        ),
    ]
