# Generated by Django 4.2.3 on 2023-08-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactsettings_agreement_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, null=True, verbose_name='Тема обращения')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст обращения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
            },
        ),
    ]
