# Generated by Django 4.2.3 on 2023-08-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_appeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='text',
        ),
    ]
