# Generated by Django 4.2.3 on 2023-08-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_remove_appeal_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactsettings',
            name='target_email',
        ),
        migrations.AddField(
            model_name='contactsettings',
            name='recipient_emails',
            field=models.EmailField(blank=True, help_text='Через запятую! На эти адреса будут приходить обращения из виртуальной приемной', max_length=254, null=True, verbose_name='Email адреса'),
        ),
    ]
