# Generated by Django 4.2.6 on 2024-05-27 08:19

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_alter_contactsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='userdata_checkbox_text',
            field=djangocms_text_ckeditor.fields.HTMLField(default='Я соглашаюсь на обработку моих персональных данных', verbose_name='Текст галочки на форме данных пользователя'),
        ),
    ]
