# Generated by Django 4.2.6 on 2024-05-27 10:24

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_alter_contactsettings_userdata_checkbox_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='agreement_checkbox_text',
            field=djangocms_text_ckeditor.fields.HTMLField(default='Я прочитал(а) правила пользования виртуальной приемной', verbose_name='Текст галочки на форме соглашения'),
        ),
    ]
