# Generated by Django 3.2.15 on 2022-09-27 19:32

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorBlocksModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_colorblocks_colorblocksmodel', serialize=False, to='cms.cmsplugin')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='ColorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Текст')),
                ('icon', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Иконка')),
                ('color', colorfield.fields.ColorField(default='#00BB00', image_field=None, max_length=18, samples=None)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_colorblocks.colorblocksmodel')),
            ],
            options={
                'verbose_name': 'цветной блок',
                'verbose_name_plural': 'цветные блоки',
            },
        ),
    ]
