# Generated by Django 3.2.15 on 2022-09-28 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_colorblocks', '0002_auto_20220928_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorblock',
            name='order',
        ),
    ]
