# Generated by Django 3.2.15 on 2022-09-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_colorblocks', '0004_auto_20220928_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorblock',
            options={'verbose_name': 'цветной блок', 'verbose_name_plural': 'цветные блоки'},
        ),
        migrations.RemoveField(
            model_name='colorblock',
            name='block_order',
        ),
        migrations.AlterField(
            model_name='colorblock',
            name='plugin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_colorblocks.colorblocksmodel'),
        ),
    ]
