# Generated by Django 3.2.15 on 2022-10-06 11:31

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_colorblocks', '0006_auto_20220928_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorblock',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
    ]
