# Generated by Django 3.2.15 on 2022-10-06 11:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_colorblocks', '0007_alter_colorblock_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorblock',
            name='color',
            field=colorfield.fields.ColorField(default='#00BB00', image_field=None, max_length=18, samples=None),
        ),
    ]
