# Generated by Django 3.2.15 on 2022-10-05 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название')),
                ('price_card', models.PositiveIntegerField(default=0, verbose_name='Цена билета по карте')),
                ('price_nocard', models.PositiveIntegerField(default=0, verbose_name='Цена билета без карты')),
                ('short_description', models.CharField(default='', max_length=1024, verbose_name='Короткое описание')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание')),
                ('main_photo', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Главное фото')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attractions.attraction')),
                ('photo', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Фото')),
            ],
        ),
    ]
