# Generated by Django 3.2.15 on 2022-10-05 08:18

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
    ]
