# Generated by Django 3.2.15 on 2022-10-05 09:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('attractions', '0002_alter_attraction_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoAttraction',
            new_name='Photo',
        ),
    ]
