# Generated by Django 3.2.15 on 2022-10-05 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_rename_photoattraction_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='image',
        ),
    ]
