# Generated by Django 3.2.15 on 2022-10-06 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('attractions', '0004_rename_photo_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='attractions_attractionsplugin', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Текст')),
                ('num_objects', models.PositiveIntegerField(default=4, verbose_name='Количество аттракционов')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.AlterModelOptions(
            name='attraction',
            options={'verbose_name': 'аттракцион', 'verbose_name_plural': 'аттракционы'},
        ),
    ]
