# Generated by Django 3.2.15 on 2022-10-06 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_attraction_placeholder_bottom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='placeholder_bottom',
        ),
    ]
