# Generated by Django 3.2.15 on 2022-10-06 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0007_remove_attraction_placeholder_bottom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attractionsplugin',
            name='text',
        ),
        migrations.RemoveField(
            model_name='attractionsplugin',
            name='title',
        ),
    ]
