# Generated by Django 3.2.15 on 2022-10-11 05:57

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('attractions', '0008_auto_20221006_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='placeholder_top',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, slotname='top', to='cms.placeholder'),
        ),
    ]
