# Generated by Django 3.2.15 on 2022-10-12 09:25

import cms.models.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('attractions', '0009_attraction_placeholder_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='placeholder_bottom',
            field=cms.models.fields.PlaceholderField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='placeholder_bottom', slotname='bottom', to='cms.placeholder'),
        ),
    ]
