# Generated by Django 3.2.15 on 2022-10-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0011_auto_20221026_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='price_kid',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена, руб/билет (дети)'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена, руб/билет (взрослый)'),
        ),
    ]
