# Generated by Django 3.2.15 on 2022-10-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0012_auto_20221026_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Если оставить равным 0 - добавится в конец.', null=True, verbose_name='Порядок'),
        ),
    ]
