# Generated by Django 3.2.15 on 2022-10-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0013_attraction_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='restrictions',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Ограничения'),
        ),
    ]
