# Generated by Django 3.2.15 on 2022-10-26 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0014_alter_attraction_restrictions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attraction',
            options={'ordering': ['order'], 'verbose_name': 'аттракцион', 'verbose_name_plural': 'аттракционы'},
        ),
    ]
