# Generated by Django 3.2.15 on 2022-10-26 07:22

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('attractions', '0015_alter_attraction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='main_photo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL, verbose_name='Главное фото'),
        ),
    ]
