# Generated by Django 3.2.15 on 2022-10-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0016_alter_attraction_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='work_in_summer',
            field=models.BooleanField(default=True, verbose_name='Работает летом?'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='work_in_winter',
            field=models.BooleanField(default=False, verbose_name='Работает зимой?'),
        ),
    ]
