# Generated by Django 3.2.15 on 2022-10-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0017_auto_20221026_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
    ]
