# Generated by Django 3.2.15 on 2022-11-02 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0021_auto_20221101_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractionsplugin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attractions.category'),
        ),
        migrations.AddField(
            model_name='attractionsplugin',
            name='season',
            field=models.CharField(choices=[('summer', 'Лето'), ('winter', 'Зима')], default='summer', max_length=16, verbose_name='Сезон'),
        ),
    ]
