# Generated by Django 3.2.15 on 2022-11-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0022_auto_20221102_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractionsplugin',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Лето'), ('winter', 'Зима')], default='summer', max_length=16, null=True, verbose_name='Сезон'),
        ),
    ]
