# Generated by Django 4.2.3 on 2023-09-29 03:56

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('layout', models.CharField(choices=[('bottom-right', 'Справа внизу'), ('top-left', 'Слева вверху'), ('top-right', 'Справа вверху'), ('bottom-left', 'Слева внизу'), ('bottom', 'Внизу во всю ширину'), ('top', 'Вверху во всю ширину')], default='bottom-right', verbose_name='Расположение')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('content', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Содержимое')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
