# Generated by Django 4.2.3 on 2023-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popup',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок'),
        ),
    ]
