# Generated by Django 4.2.3 on 2023-10-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popups', '0002_alter_popup_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='button_text',
            field=models.CharField(default='Хорошо', max_length=64, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='popup',
            name='use_button',
            field=models.BooleanField(default=True, verbose_name='Использовать кнопку'),
        ),
    ]
