# Generated by Django 4.1.7 on 2023-03-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='thumb_height',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='slide',
            name='thumb_width',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='slider',
            name='num_items',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Количество отображаемых элементов'),
        ),
    ]
