# Generated by Django 4.1.7 on 2023-03-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slide_thumb_height_slide_thumb_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='thumb_height',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='thumb_width',
            field=models.PositiveSmallIntegerField(default=200, verbose_name='Ширина'),
        ),
    ]
