# Generated by Django 4.2.3 on 2023-09-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_alter_slide_thumb_height_alter_slide_thumb_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='lightbox_on',
            field=models.BooleanField(default=True, verbose_name='Увеличивать изображение по клику'),
        ),
    ]
