# Generated by Django 4.2.3 on 2023-08-10 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Расширение файла'),
        ),
        migrations.AddField(
            model_name='document',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во загрузок'),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.documenttype', verbose_name='Тип документа'),
        ),
    ]
