# Generated by Django 4.2.3 on 2023-08-10 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_document_extension_document_hits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='extension',
        ),
    ]
