# Generated by Django 4.2.3 on 2023-08-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_remove_document_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Расширение файла'),
        ),
    ]
