# Generated by Django 4.2.3 on 2023-08-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_document_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extension',
            field=models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='Расширение файла'),
        ),
    ]
