# Generated by Django 4.2.3 on 2023-08-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_alter_document_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='hide_document_type',
            field=models.BooleanField(default=True, verbose_name='Отображать тип документа, номер и дату в названии'),
        ),
    ]
