# Generated by Django 4.2.3 on 2023-08-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_documenttype_hide_document_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='hide_document_type',
            new_name='show_document_type',
        ),
    ]
