# Generated by Django 4.2.3 on 2023-08-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='subname',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Содержание документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, help_text='Пример: "Приказ №159 от 01.01.2001"', max_length=512, null=True, verbose_name='Название'),
        ),
    ]
