# Generated by Django 4.2.3 on 2023-08-11 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_document_subname_alter_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date',
            field=models.DateField(blank=True, help_text='Укажите дату документа (если она есть)', null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='Документ', help_text='Примеры: "Приказ Минспорта РФ" , "Уставной документ", и т.д.', max_length=512, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(blank=True, help_text='Укажите номер документа (если он есть)', max_length=32, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='document',
            name='published_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subname',
            field=models.CharField(blank=True, help_text='Пример: "Об утверждении правил перевозки детей"', max_length=512, null=True, verbose_name='Содержание документа'),
        ),
    ]
