# Generated by Django 4.2.3 on 2023-08-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_alter_document_date_alter_document_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'тип документа', 'verbose_name_plural': 'типы документов'},
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='subname',
            field=models.CharField(blank=True, help_text='Пример: "Об утверждении правил перевозки детей". Без внешних кавычек.', max_length=512, null=True, verbose_name='Содержание документа'),
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
