# Generated by Django 4.2.3 on 2023-08-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_alter_document_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default='Документ', help_text='Примеры: "Приказ Минспорта РФ" , "Уставной документ", и т.д.   Номер и дату в этом поле не указывайте', max_length=512, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='subname',
            field=models.CharField(blank=True, help_text='Без внешних кавычек. Пример: Об утверждении правил перевозки детей. ', max_length=512, null=True, verbose_name='Содержание документа'),
        ),
    ]
