# Generated by Django 4.2.3 on 2023-08-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0014_taggeddocument_document_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.DeleteModel(
            name='TaggedDocument',
        ),
    ]
