# Generated by Django 4.2.3 on 2023-08-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0020_documentsplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsplugin',
            name='show_description',
            field=models.BooleanField(default=True, verbose_name='Отображать описание документов'),
        ),
        migrations.AddField(
            model_name='documentsplugin',
            name='show_icon',
            field=models.BooleanField(default=True, verbose_name='Отображать иконку документов'),
        ),
        migrations.AddField(
            model_name='documentsplugin',
            name='show_link',
            field=models.BooleanField(default=True, verbose_name='Отображать кнопку ссылки на документ'),
        ),
    ]
