# Generated by Django 4.2.3 on 2023-08-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0022_documentsplugin_show_file_attrs'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsplugin',
            name='show_tags',
            field=models.BooleanField(default=True, verbose_name='Отображать теги документа'),
        ),
    ]
