# Generated by Django 4.2.3 on 2023-08-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0023_documentsplugin_show_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentsplugin',
            name='show_link',
        ),
        migrations.AlterField(
            model_name='documentsplugin',
            name='show_description',
            field=models.BooleanField(default=False, verbose_name='Отображать описание документов'),
        ),
        migrations.AlterField(
            model_name='documentsplugin',
            name='show_tags',
            field=models.BooleanField(default=False, verbose_name='Отображать теги документа'),
        ),
    ]
