# Generated by Django 4.2.3 on 2023-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0024_remove_documentsplugin_show_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='subname',
            field=models.CharField(blank=True, help_text='Без внешних кавычек. Пример: Об утверждении правил перевозки детей. ', max_length=512, null=True, verbose_name='Описание документа'),
        ),
    ]
