# Generated by Django 4.2.3 on 2023-08-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0025_alter_document_subname'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsplugin',
            name='bootstrap_col',
            field=models.CharField(choices=[(12, 1), (6, 2), (4, 3), (3, 4), (2, 6)], default=3, max_length=8, verbose_name='Количество элементов в строке'),
        ),
    ]
