# Generated by Django 4.2.3 on 2023-08-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('docs', '0027_alter_documentsplugin_bootstrap_col'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('show_description', models.BooleanField(default=False, verbose_name='Отображать описание документа')),
                ('show_icon', models.BooleanField(default=True, verbose_name='Отображать иконку документа')),
                ('show_file_attrs', models.BooleanField(default=True, verbose_name='Отображать атрибуты файла')),
                ('show_tags', models.BooleanField(default=False, verbose_name='Отображать теги документа')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.document', verbose_name='Документ')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
