# Generated by Django 4.2.3 on 2023-09-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0029_rename_category_documentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsplugin',
            name='hide_more_button',
            field=models.BooleanField(default=False, verbose_name='Скрыть кнопку перехода к документам'),
        ),
    ]
