# Generated by Django 4.2.3 on 2023-09-05 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0030_documentsplugin_hide_more_button'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentcategory',
            options={'ordering': ['order'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
