# Generated by Django 4.2.3 on 2023-09-06 08:18

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('docs', '0031_alter_documentcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsplugin',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
