# Generated by Django 4.2.3 on 2023-09-06 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0032_documentsplugin_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsplugin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='docs.documentcategory', verbose_name='Категория'),
        ),
    ]
