# Generated by Django 4.1.7 on 2023-02-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iconextension',
            name='fa_icon',
            field=models.CharField(blank=True, default='', help_text='Названия иконок брать <a href="https://fontawesome.com/icons" target="blank">отсюда</a>', max_length=32, verbose_name='Иконка страницы'),
        ),
    ]
