# Generated by Django 4.1.7 on 2023-02-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_iconextension_fa_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=256, verbose_name='Подзаголовок')),
                ('phone', models.CharField(max_length=256, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='iconextension',
            name='fa_icon',
            field=models.CharField(blank=True, default='', help_text='Названия иконок брать <a href="https://fontawesome.com/v4/icons/" target="blank">отсюда</a>', max_length=32, verbose_name='Иконка страницы'),
        ),
    ]
