# Generated by Django 4.1.7 on 2023-02-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_alter_iconextension_fa_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='', max_length=256, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(default='', max_length=256, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='subtitle',
            field=models.CharField(default='', max_length=256, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='title',
            field=models.CharField(default='', max_length=256, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', help_text='Примеры: "ВК", "Мы в контакте", "Мы в ВК"', max_length=256, verbose_name='Текст')),
                ('url', models.URLField(verbose_name='Ссылка на страницу в соц.сети.')),
                ('icon', models.CharField(default='', help_text='Названия иконок брать <a href="https://fontawesome.com/v4/icons/" target="blank">отсюда</a>', max_length=32, verbose_name='Иконка соц.сети')),
                ('sitesettings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sitesettings')),
            ],
            options={
                'verbose_name': 'соц.сеть',
                'verbose_name_plural': 'соц.сети',
            },
        ),
    ]
