# Generated by Django 4.1.7 on 2023-06-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_sitesettings_share_mailru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='share_instagram',
        ),
    ]
