# Generated by Django 4.2.3 on 2023-08-06 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0009_remove_sitesettings_share_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemSettingsExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_icon', models.CharField(blank=True, default='', help_text='Названия иконок брать <a href="https://fontawesome.com/v4/icons/" target="blank">отсюда</a>', max_length=32, verbose_name='Иконка пункта меню')),
                ('extended_object', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cms.page')),
                ('public_extension', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft_extension', to='core.menuitemsettingsextension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='IconExtension',
        ),
    ]
