# Generated by Django 4.2.3 on 2023-08-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_menuitemsettingsextension_delete_iconextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemsettingsextension',
            name='dropdown',
            field=models.CharField(choices=[('normal', 'Обычный'), ('mega', 'Мега меню')], default='normal', max_length=10, verbose_name='Стиль выпадающего меню'),
        ),
    ]
