# Generated by Django 4.2.3 on 2023-08-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_menuitemsettingsextension_dropdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='menu_style',
            field=models.CharField(choices=[('1', 'Стиль №1'), ('2', 'Стиль №2')], default='1', max_length=10, verbose_name='Макет главного меню'),
        ),
        migrations.AlterField(
            model_name='menuitemsettingsextension',
            name='dropdown_mega',
            field=models.BooleanField(default=False, help_text='Если отмечено, выпадающее меню будет во всю ширину                                         (работает только на верхнем уровне)', verbose_name='Mega Dropdown'),
        ),
    ]
