# Generated by Django 4.2.3 on 2023-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_extendedpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedpage',
            name='test_field',
            field=models.CharField(blank=True, null=True, verbose_name='TEST_FIELD'),
        ),
    ]
