# Generated by Django 4.2.3 on 2023-08-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_extendedpage_test_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedPage',
        ),
    ]
