# Generated by Django 4.2.3 on 2023-09-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0016_delete_extendedpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('title', models.CharField(verbose_name='Заголовок')),
                ('subtitle', models.CharField(verbose_name='Подзаголовок (не обязательно)')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
