# Generated by Django 4.2.3 on 2023-09-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_headerplugin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerplugin',
            name='subtitle',
            field=models.CharField(blank=True, null=True, verbose_name='Подзаголовок (не обязательно)'),
        ),
    ]
