# Generated by Django 4.2.3 on 2023-09-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0019_remove_headerplugin_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitespacePlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('size', models.CharField(choices=[('medium', 'Средне'), ('small', 'Чуть чуть'), ('large', 'Побольше')], default='medium', verbose_name='Размер')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.RemoveField(
            model_name='headerplugin',
            name='size',
        ),
        migrations.AddField(
            model_name='headerplugin',
            name='subtitle',
            field=models.CharField(blank=True, null=True, verbose_name='Подзаголовок (не обязательно)'),
        ),
        migrations.AddField(
            model_name='headerplugin',
            name='title',
            field=models.CharField(default=' ', verbose_name='Заголовок'),
        ),
    ]
