# Generated by Django 4.2.3 on 2023-09-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_headerplugin_align_headerplugin_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerplugin',
            name='layout',
            field=models.CharField(choices=[('bold-line', 'С жирной линией'), ('thin-line', 'С тонкой линией'), ('no-line', 'Без линии')], default='bold-line', verbose_name='Стиль'),
        ),
    ]
