# Generated by Django 4.2.3 on 2023-09-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0022_alter_headerplugin_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmenuPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('layout', models.CharField(choices=[('blocks', 'Блоки'), ('list', 'Список')], default='blocks', verbose_name='Макет')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
