# Generated by Django 4.2.3 on 2023-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_submenuplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenuplugin',
            name='parent_page',
            field=models.CharField(blank=True, help_text='Указывается идентификатор страницы, дочернее меню которой будет отображено.                                 (ID заполняется в расширенных настройках страницы). Если не указано, будет отображено                                 дочернее меню текущей страницы', max_length=32, null=True, verbose_name='ID родителя (не обязательно)'),
        ),
    ]
