# Generated by Django 4.2.3 on 2023-09-21 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_purecodeplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='purecodeplugin',
            name='css',
            field=models.TextField(blank=True, null=True, verbose_name='CSS'),
        ),
        migrations.AddField(
            model_name='purecodeplugin',
            name='js',
            field=models.TextField(blank=True, null=True, verbose_name='CSS'),
        ),
    ]
