# Generated by Django 4.2.3 on 2023-09-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('core', '0027_alter_purecodeplugin_code_alter_purecodeplugin_js'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabsPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin')),
                ('tabs_position', models.CharField(choices=[('top', 'Сверху'), ('left', 'Слева'), ('right', 'Справа'), ('bottom', 'Снизу')], default='top', max_length=32, verbose_name='Расположение переключателей вкладок')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
