# Generated by Django 4.2.3 on 2023-09-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tabplugin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabsplugin',
            name='tabs_position',
        ),
        migrations.AddField(
            model_name='tabsplugin',
            name='justified',
            field=models.BooleanField(default=True, verbose_name='Растянуть строку переключателей вкладок во всю ширину'),
        ),
    ]
