# Generated by Django 4.2.3 on 2023-09-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_accordionplugin_itemaccordionplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='accordionplugin',
            name='auto_open',
            field=models.BooleanField(default=True, verbose_name='Автоматически открывать вкладку при загрузке'),
        ),
        migrations.AddField(
            model_name='accordionplugin',
            name='num_auto_open',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер вкладки'),
        ),
    ]
