# Generated by Django 4.2.3 on 2023-09-18 02:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название мероприятия')),
                ('place', models.CharField(blank=True, max_length=256, null=True, verbose_name='Место проведения')),
                ('start_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время начала мероприятия')),
                ('finish_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время окончания мероприятия')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('poster', filer.fields.image.FilerImageField(blank=True, help_text='Если оставить пустым, будет использовано изображение из альбома', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Обложка')),
            ],
            options={
                'verbose_name': 'мероприятие',
                'verbose_name_plural': 'мероприятия',
            },
        ),
    ]
