# Generated by Django 4.2.3 on 2023-09-19 09:18

from django.db import migrations
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_upcomingeventsplugin_alter_event_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='finish_at',
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
