# Generated by Django 4.2.3 on 2023-10-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_categoryevent_event_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryevent',
            options={'verbose_name': 'категория мероприятий', 'verbose_name_plural': 'категории мероприятий'},
        ),
    ]
