# Generated by Django 4.2.3 on 2023-10-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_dayevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayevent',
            options={'ordering': ['start_at'], 'verbose_name': 'день', 'verbose_name_plural': 'дни мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'мероприятие', 'verbose_name_plural': 'мероприятия'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_at',
        ),
    ]
