# Generated by Django 4.2.3 on 2023-10-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_dayevent_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayevent',
            name='postfix_name',
            field=models.CharField(blank=True, null=True, verbose_name='Постфикс названия'),
        ),
    ]
