# Generated by Django 4.2.3 on 2023-10-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_dayevent_postfix_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='postfix_name',
            field=models.CharField(blank=True, null=True, verbose_name='Постфикс'),
        ),
    ]
