# Generated by Django 4.2.3 on 2023-10-09 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_alter_dayevent_postfix_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала мероприятия'),
        ),
    ]
