# Generated by Django 4.2.9 on 2024-11-06 04:42

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_dayevent_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayevent',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, null=True),
        ),
    ]
