# Generated by Django 4.2.9 on 2024-11-18 04:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_dayevent_recurrences'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала мероприятия')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('place', models.CharField(blank=True, max_length=256, null=True, verbose_name='Место проведения')),
                ('postfix_name', models.CharField(blank=True, help_text='Пример: День 1, Второй этап и т.д.                                                Будет отображено в квадратных скобках в                                                конце названия мероприятия.', null=True, verbose_name='Постфикс названия мероприятия')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('recurrences', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'verbose_name': 'день',
                'verbose_name_plural': 'дни мероприятия',
                'ordering': ['start_time'],
            },
        ),
        migrations.DeleteModel(
            name='DayEvent',
        ),
    ]
