# Generated by Django 4.2.9 on 2024-11-21 07:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_sessionevent_delete_dayevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.sessionevent')),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
    ]
