# Generated by Django 4.2.9 on 2024-11-26 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_evententry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionevent',
            options={'ordering': ['event'], 'verbose_name': 'сессия', 'verbose_name_plural': 'сессии'},
        ),
        migrations.RemoveField(
            model_name='sessionevent',
            name='start_at',
        ),
        migrations.AlterField(
            model_name='sessionevent',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 0), verbose_name='Время начала'),
        ),
    ]
