# Generated by Django 4.2.9 on 2024-11-26 14:40

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_alter_sessionevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionevent',
            name='recurrences',
            field=recurrence.fields.RecurrenceField(blank=True, null=True, verbose_name='Правила применения'),
        ),
    ]
