# Generated by Django 4.2.9 on 2024-12-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_alter_sessionevent_recurrences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evententry',
            options={'ordering': ['session__start_time']},
        ),
    ]
