# Generated by Django 4.2.9 on 2024-12-03 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_evententry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evententry',
            options={'ordering': ['start_at', 'session__start_time']},
        ),
    ]
